### ISSUE TITLE
Hydrus API support

### ISSUE THREAD

**Issue by CuddleBear92** [nostrenz/hatate-iqdb-tagger#1]
Can you add Hydrus API support?
Would enable more automation on the client side without the need of folders and file creation at all.

Should be able to search up any query inside Hydrus and pull the files for IQDB lookup and such then send the resulting URL to the client for automated URL download.

EDIT: adding API link: http://hydrusnetwork.github.io/hydrus/help/client_api.html

**Comment by nostrenz** [comment]
I'm definitely interested in implementing the API.

I originally just made this little project to help me move into Hydrus the thousands of file still sitting in folders waiting to be tagged, but I'd like to improve it with a better Hydrus integration.

**Comment by nostrenz** [comment]
I've released a new version with the API support.
Hopefully this makes it more useful than before!

**Comment by CuddleBear92** [comment]
closing this one as you did add support for it after all.
