### ISSUE TITLE
Sending Danbooru URL to Hydrus Through API Sends Unparsable URL

### ISSUE THREAD

**Issue by ColonelCthulu** [nostrenz/hatate-iqdb-tagger#10]
I was having an issue where I would use Hatate, and then send the URL to Hydrus using the API, but the images would not be imported. I looked at the import log and found that many of them are being ignored because "Looks like HTML -- maybe the client needs to be taught how to parse this?" and the URL is along the lines of "https://danbooru.donmai.us/post/show/xxxxxx".

I believe the "show" part of the URL is causing the issue. I am unsure if this is a setting in Hydrus I need to fix or if it is a bug of Hatate. It would seem to me that removing the "/show" substring would resolve this issue when sending the URL to Hydrus.

See below for example of my log, specifically the "ignored" entries.

![image](https://user-images.githubusercontent.com/26289488/129059053-9f636809-bd72-45d8-906c-e953a483e818.png)

**Comment by nostrenz** [comment]
This was a problem with SauceNAO searches as they return Danbooru URLs like `/post/show/xxxxxx` which get redirected to `/posts/xxxxxx`.

Thanks for reporting the issue, I made a new release to fix this.

**Comment by ColonelCthulu** [comment]
Wonderful, thank you for the quick response and update.
I'll give it a try again tomorrow when my SauceNao limit resets, and I'll close this issue once I've verified.
