### ISSUE TITLE
Release 5 Triggers Ransomware Alert in MalwareBytes

### ISSUE THREAD

**Issue by ColonelCthulu** [nostrenz/hatate-iqdb-tagger#12]
I was running the latest release and suddenly the process stopped and MalwareBytes popped up saying it quarantined it because of "Generic Ransomware". I'm sure this is a false positive, but I'm unsure if there is anything you can do on your end about it.

![image](https://user-images.githubusercontent.com/26289488/129738858-ade1fc62-3a07-45c6-afd7-8eee8a368a61.png)

**Comment by nostrenz** [comment]
Those kind of false positive report happen sometimes, sadly there's really nothing I can do to prevent it. The only solution is to add the executable as an exception.

**Comment by ColonelCthulu** [comment]
I figured this might be the case, I appreciate the information.
