### ISSUE TITLE
SauceNao tags not added

### ISSUE THREAD

**Issue by WorldTeacher** [nostrenz/hatate-iqdb-tagger#14]
I tested the SauceNao with 280 images and Hatate says that the images were not found, however when I search for them manually, Ican see them on Saucenao and access the tags. I will test again later, will close this issue if I can fix this myself. If not, I'll add a comment and elaborate

**Comment by Drakonas** [comment]
If you go into the Hatate settings and enable all the sources before you query/add the images, you'll find it starts adding the tags from SauceNAO sources automatically.
