### ISSUE TITLE
Images duplicate when adding more than one image

### ISSUE THREAD

**Issue by thefloattube** [nostrenz/hatate-iqdb-tagger#15]
Adding more than one image will sometimes cause different images to appear as the same in the thumbnails. Running the program like this will match the file and tag it as the incorrect picture.
![image](https://user-images.githubusercontent.com/96643521/147378283-82df10f9-8747-4594-bfe0-8d0117c62653.png)

**Comment by nostrenz** [comment]
Hi, thanks for the report! I made a new release which fixes that.

**Comment by thefloattube** [comment]
Oh wow, thanks for the quick fix!
