### ISSUE TITLE
URL send mode

### ISSUE THREAD

**Issue by CuddleBear92** [nostrenz/hatate-iqdb-tagger#2]
An Alternative for the API mode would be an URL export mode which just lists all the matched urls by its criteria in a single text file or text files split on site.

This makes sense for easy imports if you dont want to add the API support for automation. 
Would remove the need to manually import the files with the sidecar files but rather enable users to dump the files un-tagged and download the tags direct from the site its the latest parsers.

**Comment by nostrenz** [comment]
Supporting both modes would be nice to cover more use cases, I'll look into that as well.

**Comment by CuddleBear92** [comment]
renaming and expanding on this.
Sending the result urls from Hatate with the Client API into Hydrus is prob the way to go. Allowing the download system to take over and be ruled by the default tag import options and everything.

Would also lower the API requests needed for many different things.

Think such an option should not send tags at all, it could also operate in a much less restricted manner. allowing you to set a lower % of matches as different files that doesnt match doesnt really cause issues in that case as you dont append it to a file at all.
