### ISSUE TITLE
saucenao addition? 

### ISSUE THREAD

**Issue by CuddleBear92** [nostrenz/hatate-iqdb-tagger#5]
could Saucenao be added as a source for more options?
https://saucenao.com/

Would make sense to add more sources here in the game GUI for the ease of use.

**Comment by nostrenz** [comment]
I finally implemented it, as the whole program was basically useless since IQDB is down.

**Comment by OuterNeptunium** [comment]
Just would like to add to this: More index toggle options for the SauceNao option would be very helpful, especially since there are some indices without tags (such as deviantArt) included under the "Other Sources" option.

**Comment by nostrenz** [comment]
I've added a little more sources in the Options window, and for unrecognized sources the dropdown under the match image will display the source page's domain instead of just "Other".
